#!/bin/sh
cd /

function install() {
	centos=`cat /etc/redhat-release`
    XT=`cat /etc/redhat-release | awk '{print $3}'| cut -b1`
	H=`cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l`
	HX=`cat /proc/cpuinfo | grep "core id" |wc -l`
	DD=`df -h /`
    W=`getconf LONG_BIT`
	G=`awk '/MemTotal/{printf("%1.1fG\n",$2/1024/1024)}' /proc/meminfo`
	SJ=`date '+%Y-%m-%d %H:%M:%S'`
	  IP=`curl -s http://v4.ipv6-test.com/api/myip.php`
    if [ -z $IP ]; then
    IP=`curl -s https://www.boip.net/api/myip`
    fi
	echo "
================================服务器配置================================
  
System Version：$centos   $W 位


CPU number：$H个

CPU core：$HX核

Running Memory：$G

===============================硬盘使用情况===============================
$DD	"
	done
	servicel
	service2
	service3
}

function servicel() {
	if [ "$XT" = "5" ] ; then
		centos5
	elif [ "$XT" = "6" ] ; then
		centos6
	elif [ "$XT" = "r" ] ; then
		centos7
    else
        exit 0
    fi
}
	
function centos5() {
	echo " "
	echo " "
	echo "Detected system is centos 5"
	echo " "
	cd /
	echo "Decompressing one-click file"
	tar -zxvf DNFServer.tar.gz
	cd /home/neople
	sed -i "s/101.200.211.94/${IP}/g" `find . -type f -name "*.cfg"`
	sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux
	setenforce 0
	echo " "
	echo "Decompressing the one-click file is complete"
	echo " "
	echo "Start creating virtual memory"
	echo "Please be patient here, the fastest is 1-10 minutes, the slowest is about 30 minutes."
	mkdir /swap
	dd if=/dev/zero of=/swap/mySwap bs=1M count=8192
	mkswap /swap/mySwap
	swapon /swap/mySwap
	sed -i '$a /swap/mySwap swap swap default 0 0' /etc/fstab
	echo " "
	echo "Creating virtual memory is complete"
	echo " "
	yum makecache
	yum -y install glibc.i386
	yum -y install xulrunner.i386
	yum -y install libXtst
	yum -y install gcc gcc-c++ make zlib-devel
	yes y | head -1 | yum remove mysql mysql-* -y;
	echo " "
	echo "Start turning off the firewall"
	echo " "
	service iptables stop
	chkconfig iptables off
	echo " "
	echo "Firewall shutdown complete"
	echo " "
	cd
	echo 1 > /proc/sys/vm/drop_caches
}

function centos6() {
	echo " "
	echo "Detected system is centos 6"
	echo " "
	cd /
	echo "Decompressing one-click file"
	tar -zxvf DNFServer.tar.gz
	cd /home/neople
	sed -i "s/101.200.211.94/${IP}/g" `find . -type f -name "*.cfg"`
	sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux
	setenforce 0
	echo " "
	echo "Decompressing the one-click file is complete"
	echo " "
	echo "Start creating virtual memory"
	echo "Please be patient here, the fastest is 1-10 minutes, the slowest is about 30 minutes."
	mkdir /swap
	dd if=/dev/zero of=/swap/mySwap bs=1M count=8192
	mkswap /swap/mySwap
	swapon /swap/mySwap
	sed -i '$a /swap/mySwap swap swap default 0 0' /etc/fstab
	echo " "
	echo "Creating virtual memory is complete"
	echo " "
	yum makecache
	yum -y install glibc.i686
	yum -y install xulrunner.i686
	yum -y install libXtst
	yum -y install gcc gcc-c++ make zlib-devel
	yes y | head -1 | yum remove mysql mysql-* -y;
	echo " "
	echo "Start turning off the firewall"
	echo " "
	service iptables stop
	chkconfig iptables off
	echo " "
	echo "Firewall shutdown complete"
	echo " "
	cd
	echo 1 > /proc/sys/vm/drop_caches
}

function centos7() {
	echo " "
	echo "Detected system is centos 7"
	echo " "
	cd /
	echo "Decompressing one-click file"
	tar -zxvf DNFServer.tar.gz
	cd /home/neople
	sed -i "s/101.200.211.94/${IP}/g" `find . -type f -name "*.cfg"`
	sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux
	setenforce 0
	echo " "
	echo "Decompressing the one-click file is complete"
	echo " "
	echo "Start creating virtual memory"
	echo "Please be patient here, the fastest is 1-10 minutes, the slowest is about 30 minutes."
	mkdir /swap
	dd if=/dev/zero of=/swap/mySwap bs=1M count=8192
	mkswap /swap/mySwap
	swapon /swap/mySwap
	sed -i '$a /swap/mySwap swap swap default 0 0' /etc/fstab
	echo " "
	echo "Creating virtual memory is complete"
	echo " "
	yum makecache
	yum -y install glibc.i686
	yum -y install xulrunner.i686
	yum -y install libXtst
	yum -y install gcc gcc-c++ make zlib-devel
	yes y | head -1 | yum remove mysql mysql-* -y;
	echo " "
	echo "Start turning off the firewall"
	echo " "
	systemctl disable firewalld
	systemctl stop firewalld
	systemctl disable firewalld.service
	systemctl stop firewalld.service
	echo " "
	echo "Firewall shutdown complete"
	echo " "
	cd
	echo 1 > /proc/sys/vm/drop_caches
}

function service2() {
  cd /
  chmod -R 0777 /home
  chmod -R 0777 /root
  chmod -R 0777 /opt/lampp
  cd /home/GeoIP-1.4.8/
  ./configure
  make&& make check && make install
}

function service3() {
 echo -n "	Complete installation, whether to delete temporary files y/n [n] ?"
    read ANS
    case $ANS in
    y|Y|yes|Yes)
    rm -f /DNFServer.tar.gz
	rm -f /install
    ;;
    n|N|no|No)
    ;;
    *)
    ;;
    esac 
}

install
	echo "The game is set up, please see the instructions for the remaining steps."
